version: '3'
services:
  web:
    platform: linux/amd64
    image: nginx:1.21
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html

  app:
    platform: linux/amd64
    build: ./php
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html

  db:
    platform: linux/amd64
    # image: mysql:8.0 
    build: ./mysql
    # environment:
    #   MYSQL_ROOT_PASSWORD: password
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/data:/var/lib/mysql
      
  mailhog:
    container_name: docker-compose-mailhog-mailhog
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
  
